### ISSUE TITLE
Milestone 2 Shiny app review

### ISSUE THREAD

**Issue by johannesharmse** [avinashkz/crime_shiny_app#2]
> The use of the green and white colours in the colour scheme has been applied very well. The green stands out well against the white background and the different shades contribute well towards the intuitive user interface.
>
> The radio buttons and date range slider widgets are appropriate for the types of variables and features being filtered for. I would personally reconsider the placement of the graph aesthetics widget. It might make more sense to place it in the same panel, as the graph that is reacting to this user input.
>
> It is unfortunate that the title of the app is being cut off on certain screen sizes. The title is the first text that catches the user's eye, so it would be worthwhile resolving this issue.
>
> The hovering functionality on the map and trend graph is a great way of effortlessly providing summary information to the user. The data filtering click functionality on the map is another intuitive way for the user to interact with the app.
>
> A suggestion would be to either link the data displayed in the table to the filtering criteria used for the map and graph, or remove the displayed filtering panel when the user clicks on the data table tab.
>
> In summary, the app provides a pleasant user experience in terms of reactivity speed, ease-of-use, and easy to understand visualizations, for any person who might be interested in gaining new insight into crime data, no matter the user's level of domain expertise.

**Comment by avinashkz** [comment]
Completed Enhancements and fixed bugs.
